language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "3.3"
    - os: linux
      sudo: required
      dist: trusty
      python: "3.4"
    - os: linux
      sudo: required
      dist: trusty
      python: "3.5"
    # - os: osx
    #   osx_image: xcode7.2
    #   language: generic

addons:
  apt:
    packages:
      - build-essential
      - gdb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; sudo apt-get install lldb-3.4 ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install mock pexpect nose ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install mock pexpect nose  --user; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install . --user; fi

script:
  - python --version
  - mkdir ~/.voltron
  - echo '{"general":{"debug_logging":true}}' >~/.voltron/config
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -m nose -sv tests/gdb_cli_tests.py ; fi
  - python -m nose -sv tests/lldb_cli_tests.py
